// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answer.sql

package store

import (
	"context"
)

type InsertAnswersParams struct {
	AttemptID        string  `json:"attemptId"`
	QuestionID       string  `json:"questionId"`
	SelectedOptionID *string `json:"selectedOptionId"`
	Correct          *bool   `json:"correct"`
}

const listAnswersByAttempt = `-- name: ListAnswersByAttempt :many
SELECT id, attempt_id, question_id, selected_option_id, correct FROM answer
WHERE attempt_id = $1
ORDER BY question_id
`

// ListAnswersByAttempt returns every answer recorded for an attempt.
func (q *Queries) ListAnswersByAttempt(ctx context.Context, attemptID string) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedOptionID,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
