// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package store

import (
	"context"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO message (conversation_id, role, text, citations)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, role, text, citations, created_at
`

type AppendMessageParams struct {
	ConversationID string `json:"conversationId"`
	Role           string `json:"role"`
	Text           string `json:"text"`
	Citations      []byte `json:"citations"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.ConversationID,
		arg.Role,
		arg.Text,
		arg.Citations,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Text,
		&i.Citations,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one

INSERT INTO conversation (subject_id, student_id)
VALUES ($1, $2)
RETURNING id, subject_id, student_id, created_at
`

type CreateConversationParams struct {
	SubjectID string `json:"subjectId"`
	StudentID string `json:"studentId"`
}

// Conversation + Message queries (D01) — contract 2-C01.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.SubjectID, arg.StudentID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.StudentID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, subject_id, student_id, created_at FROM conversation
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.StudentID,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, text, citations, created_at FROM message
WHERE conversation_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListMessages(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Text,
			&i.Citations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
