// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertAnswers implements pgx.CopyFromSource.
type iteratorForInsertAnswers struct {
	rows                 []InsertAnswersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertAnswers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertAnswers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AttemptID,
		r.rows[0].QuestionID,
		r.rows[0].SelectedOptionID,
		r.rows[0].Correct,
	}, nil
}

func (r iteratorForInsertAnswers) Err() error {
	return nil
}

// answer.sql — queries for the answer table (D08, contract C06).
// InsertAnswers bulk-inserts all answers for an attempt in a single round trip
// (pgx COPY). Submit grades every question and writes the whole set at once;
// the unique(attempt_id, question_id) constraint guarantees at most one answer
// per question per attempt.
func (q *Queries) InsertAnswers(ctx context.Context, arg []InsertAnswersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"answer"}, []string{"attempt_id", "question_id", "selected_option_id", "correct"}, &iteratorForInsertAnswers{rows: arg})
}
