// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_attempt.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countByStudent = `-- name: CountByStudent :one
SELECT count(*) FROM exam_attempt
WHERE student_id = $1
`

func (q *Queries) CountByStudent(ctx context.Context, studentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countByStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttempt = `-- name: CreateAttempt :one

INSERT INTO exam_attempt (
    exam_definition_id,
    student_id,
    question_ids
) VALUES (
    $1, $2, $3
)
RETURNING id, exam_definition_id, student_id, status, question_ids, score_pct, passed, per_topic, cooldown_until, started_at, submitted_at
`

type CreateAttemptParams struct {
	ExamDefinitionID string   `json:"examDefinitionId"`
	StudentID        string   `json:"studentId"`
	QuestionIds      []string `json:"questionIds"`
}

// ExamAttempt queries (D07, contract C06).
// Supports the exam loop: start, fetch, submit (grade), history, cooldown lookup.
func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.ExamDefinitionID, arg.StudentID, arg.QuestionIds)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamDefinitionID,
		&i.StudentID,
		&i.Status,
		&i.QuestionIds,
		&i.ScorePct,
		&i.Passed,
		&i.PerTopic,
		&i.CooldownUntil,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, exam_definition_id, student_id, status, question_ids, score_pct, passed, per_topic, cooldown_until, started_at, submitted_at FROM exam_attempt
WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamDefinitionID,
		&i.StudentID,
		&i.Status,
		&i.QuestionIds,
		&i.ScorePct,
		&i.Passed,
		&i.PerTopic,
		&i.CooldownUntil,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const getLastFailedForExam = `-- name: GetLastFailedForExam :one
SELECT id, exam_definition_id, student_id, status, question_ids, score_pct, passed, per_topic, cooldown_until, started_at, submitted_at FROM exam_attempt
WHERE exam_definition_id = $1
  AND student_id = $2
  AND status = 'submitted'
  AND passed = false
ORDER BY submitted_at DESC
LIMIT 1
`

type GetLastFailedForExamParams struct {
	ExamDefinitionID string `json:"examDefinitionId"`
	StudentID        string `json:"studentId"`
}

func (q *Queries) GetLastFailedForExam(ctx context.Context, arg GetLastFailedForExamParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, getLastFailedForExam, arg.ExamDefinitionID, arg.StudentID)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamDefinitionID,
		&i.StudentID,
		&i.Status,
		&i.QuestionIds,
		&i.ScorePct,
		&i.Passed,
		&i.PerTopic,
		&i.CooldownUntil,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const listByStudent = `-- name: ListByStudent :many
SELECT id, exam_definition_id, student_id, status, question_ids, score_pct, passed, per_topic, cooldown_until, started_at, submitted_at FROM exam_attempt
WHERE student_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListByStudentParams struct {
	StudentID string `json:"studentId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListByStudent(ctx context.Context, arg ListByStudentParams) ([]ExamAttempt, error) {
	rows, err := q.db.Query(ctx, listByStudent, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamAttempt{}
	for rows.Next() {
		var i ExamAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ExamDefinitionID,
			&i.StudentID,
			&i.Status,
			&i.QuestionIds,
			&i.ScorePct,
			&i.Passed,
			&i.PerTopic,
			&i.CooldownUntil,
			&i.StartedAt,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmitted = `-- name: MarkSubmitted :one
UPDATE exam_attempt
SET status         = 'submitted',
    score_pct      = $2,
    passed         = $3,
    per_topic      = $4,
    cooldown_until = $5,
    submitted_at   = now()
WHERE id = $1
RETURNING id, exam_definition_id, student_id, status, question_ids, score_pct, passed, per_topic, cooldown_until, started_at, submitted_at
`

type MarkSubmittedParams struct {
	ID            string             `json:"id"`
	ScorePct      *int32             `json:"scorePct"`
	Passed        *bool              `json:"passed"`
	PerTopic      []byte             `json:"perTopic"`
	CooldownUntil pgtype.Timestamptz `json:"cooldownUntil"`
}

func (q *Queries) MarkSubmitted(ctx context.Context, arg MarkSubmittedParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, markSubmitted,
		arg.ID,
		arg.ScorePct,
		arg.Passed,
		arg.PerTopic,
		arg.CooldownUntil,
	)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamDefinitionID,
		&i.StudentID,
		&i.Status,
		&i.QuestionIds,
		&i.ScorePct,
		&i.Passed,
		&i.PerTopic,
		&i.CooldownUntil,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}
