// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_definition.sql

package store

import (
	"context"
)

const countExamDefinitionsBySubject = `-- name: CountExamDefinitionsBySubject :one
SELECT count(*) FROM exam_definition
WHERE subject_id = $1
`

func (q *Queries) CountExamDefinitionsBySubject(ctx context.Context, subjectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countExamDefinitionsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExamDefinition = `-- name: CreateExamDefinition :one
INSERT INTO exam_definition (
    subject_id,
    name,
    type,
    scope_topic_ids,
    size,
    pass_bar,
    cooldown_min,
    reward_style
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, subject_id, name, type, scope_topic_ids, size, pass_bar, cooldown_min, reward_style, created_at
`

type CreateExamDefinitionParams struct {
	SubjectID     string   `json:"subjectId"`
	Name          string   `json:"name"`
	Type          string   `json:"type"`
	ScopeTopicIds []string `json:"scopeTopicIds"`
	Size          int32    `json:"size"`
	PassBar       int32    `json:"passBar"`
	CooldownMin   int32    `json:"cooldownMin"`
	RewardStyle   string   `json:"rewardStyle"`
}

func (q *Queries) CreateExamDefinition(ctx context.Context, arg CreateExamDefinitionParams) (ExamDefinition, error) {
	row := q.db.QueryRow(ctx, createExamDefinition,
		arg.SubjectID,
		arg.Name,
		arg.Type,
		arg.ScopeTopicIds,
		arg.Size,
		arg.PassBar,
		arg.CooldownMin,
		arg.RewardStyle,
	)
	var i ExamDefinition
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.Type,
		&i.ScopeTopicIds,
		&i.Size,
		&i.PassBar,
		&i.CooldownMin,
		&i.RewardStyle,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExamDefinition = `-- name: DeleteExamDefinition :exec
DELETE FROM exam_definition
WHERE id = $1
`

func (q *Queries) DeleteExamDefinition(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteExamDefinition, id)
	return err
}

const getExamDefinition = `-- name: GetExamDefinition :one
SELECT id, subject_id, name, type, scope_topic_ids, size, pass_bar, cooldown_min, reward_style, created_at FROM exam_definition
WHERE id = $1
`

func (q *Queries) GetExamDefinition(ctx context.Context, id string) (ExamDefinition, error) {
	row := q.db.QueryRow(ctx, getExamDefinition, id)
	var i ExamDefinition
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.Type,
		&i.ScopeTopicIds,
		&i.Size,
		&i.PassBar,
		&i.CooldownMin,
		&i.RewardStyle,
		&i.CreatedAt,
	)
	return i, err
}

const listExamDefinitionsBySubject = `-- name: ListExamDefinitionsBySubject :many
SELECT id, subject_id, name, type, scope_topic_ids, size, pass_bar, cooldown_min, reward_style, created_at FROM exam_definition
WHERE subject_id = $1
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListExamDefinitionsBySubjectParams struct {
	SubjectID string `json:"subjectId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListExamDefinitionsBySubject(ctx context.Context, arg ListExamDefinitionsBySubjectParams) ([]ExamDefinition, error) {
	rows, err := q.db.Query(ctx, listExamDefinitionsBySubject, arg.SubjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamDefinition{}
	for rows.Next() {
		var i ExamDefinition
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.Type,
			&i.ScopeTopicIds,
			&i.Size,
			&i.PassBar,
			&i.CooldownMin,
			&i.RewardStyle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExamDefinition = `-- name: UpdateExamDefinition :one
UPDATE exam_definition
SET
    name            = $2,
    type            = $3,
    scope_topic_ids = $4,
    size            = $5,
    pass_bar        = $6,
    cooldown_min    = $7,
    reward_style    = $8
WHERE id = $1
RETURNING id, subject_id, name, type, scope_topic_ids, size, pass_bar, cooldown_min, reward_style, created_at
`

type UpdateExamDefinitionParams struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Type          string   `json:"type"`
	ScopeTopicIds []string `json:"scopeTopicIds"`
	Size          int32    `json:"size"`
	PassBar       int32    `json:"passBar"`
	CooldownMin   int32    `json:"cooldownMin"`
	RewardStyle   string   `json:"rewardStyle"`
}

func (q *Queries) UpdateExamDefinition(ctx context.Context, arg UpdateExamDefinitionParams) (ExamDefinition, error) {
	row := q.db.QueryRow(ctx, updateExamDefinition,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ScopeTopicIds,
		arg.Size,
		arg.PassBar,
		arg.CooldownMin,
		arg.RewardStyle,
	)
	var i ExamDefinition
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.Type,
		&i.ScopeTopicIds,
		&i.Size,
		&i.PassBar,
		&i.CooldownMin,
		&i.RewardStyle,
		&i.CreatedAt,
	)
	return i, err
}
