// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_blob.sql

package store

import (
	"context"
)

const createBlob = `-- name: CreateBlob :one

INSERT INTO file_blob (ref, filename, content_type, size_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, ref, filename, content_type, size_bytes, created_at
`

type CreateBlobParams struct {
	Ref         string `json:"ref"`
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
	SizeBytes   int64  `json:"sizeBytes"`
}

// File blob queries (D08) — contract 2-D08.
func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) (FileBlob, error) {
	row := q.db.QueryRow(ctx, createBlob,
		arg.Ref,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i FileBlob
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlob = `-- name: DeleteBlob :exec
DELETE FROM file_blob
WHERE id = $1
`

func (q *Queries) DeleteBlob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBlob, id)
	return err
}

const getBlob = `-- name: GetBlob :one
SELECT id, ref, filename, content_type, size_bytes, created_at FROM file_blob
WHERE id = $1
`

func (q *Queries) GetBlob(ctx context.Context, id string) (FileBlob, error) {
	row := q.db.QueryRow(ctx, getBlob, id)
	var i FileBlob
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
