// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guidance.sql

package store

import (
	"context"
)

const createGuidance = `-- name: CreateGuidance :one

INSERT INTO guidance (scope, subject_id, text)
VALUES ($1, $2, $3)
RETURNING id, scope, subject_id, text, created_at
`

type CreateGuidanceParams struct {
	Scope     string  `json:"scope"`
	SubjectID *string `json:"subjectId"`
	Text      string  `json:"text"`
}

// Guidance queries (D05) — contract 2-C07.
func (q *Queries) CreateGuidance(ctx context.Context, arg CreateGuidanceParams) (Guidance, error) {
	row := q.db.QueryRow(ctx, createGuidance, arg.Scope, arg.SubjectID, arg.Text)
	var i Guidance
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.SubjectID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuidance = `-- name: DeleteGuidance :exec
DELETE FROM guidance
WHERE id = $1
`

func (q *Queries) DeleteGuidance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGuidance, id)
	return err
}

const listGuidance = `-- name: ListGuidance :many
SELECT id, scope, subject_id, text, created_at FROM guidance
WHERE ($1::text IS NULL OR scope = $1::text)
  AND ($2::text IS NULL OR subject_id = $2::text)
ORDER BY created_at DESC, id DESC
`

type ListGuidanceParams struct {
	Scope     *string `json:"scope"`
	SubjectID *string `json:"subjectId"`
}

// Optionally filtered by scope and/or subject. When a narg is NULL the
// corresponding filter is skipped. Newest first.
func (q *Queries) ListGuidance(ctx context.Context, arg ListGuidanceParams) ([]Guidance, error) {
	rows, err := q.db.Query(ctx, listGuidance, arg.Scope, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guidance{}
	for rows.Next() {
		var i Guidance
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.SubjectID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
