// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
)

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE job
SET
    status     = 'processing',
    attempts   = attempts + 1,
    updated_at = now()
WHERE id = (
    SELECT id FROM job
    WHERE status = 'queued'
      AND run_after <= now()
    ORDER BY run_after ASC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at
`

// Atomically claim the oldest runnable queued job and mark it processing.
// FOR UPDATE SKIP LOCKED lets multiple workers run concurrently without contention.
func (q *Queries) ClaimNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.SubjectID,
		&i.Payload,
		&i.Result,
		&i.Progress,
		&i.Error,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE job
SET
    status     = 'ready',
    progress   = 100,
    result     = $1,
    error      = NULL,
    updated_at = now()
WHERE id = $2
RETURNING id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at
`

type CompleteJobParams struct {
	Result []byte `json:"result"`
	ID     string `json:"id"`
}

// Mark a job ready and store its result payload.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.Result, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.SubjectID,
		&i.Payload,
		&i.Result,
		&i.Progress,
		&i.Error,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO job (type, subject_id, payload, run_after)
VALUES (
    $1,
    $2,
    COALESCE($3, '{}'::jsonb),
    COALESCE($4, now())
)
RETURNING id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at
`

type EnqueueJobParams struct {
	Type      string      `json:"type"`
	SubjectID *string     `json:"subjectId"`
	Payload   interface{} `json:"payload"`
	RunAfter  interface{} `json:"runAfter"`
}

// Job queue queries (D03) — contract 2-C03. Drives the 2-F06 worker.
// Schedule a new job. run_after defaults to now() when NULL is passed.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Type,
		arg.SubjectID,
		arg.Payload,
		arg.RunAfter,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.SubjectID,
		&i.Payload,
		&i.Result,
		&i.Progress,
		&i.Error,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE job
SET
    status     = 'error',
    error      = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at
`

type FailJobParams struct {
	Error *string `json:"error"`
	ID    string  `json:"id"`
}

// Mark a job errored and store the failure message.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, failJob, arg.Error, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.SubjectID,
		&i.Payload,
		&i.Result,
		&i.Progress,
		&i.Error,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at FROM job
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.SubjectID,
		&i.Payload,
		&i.Result,
		&i.Progress,
		&i.Error,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at FROM job
WHERE ($3::text IS NULL OR subject_id = $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
	SubjectID *string `json:"subjectId"`
}

// Optionally filtered by subject, newest first.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.SubjectID,
			&i.Payload,
			&i.Result,
			&i.Progress,
			&i.Error,
			&i.Attempts,
			&i.RunAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobProgress = `-- name: UpdateJobProgress :one
UPDATE job
SET
    progress   = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, type, status, subject_id, payload, result, progress, error, attempts, run_after, created_at, updated_at
`

type UpdateJobProgressParams struct {
	Progress int32  `json:"progress"`
	ID       string `json:"id"`
}

// Report incremental progress (0-100) while processing.
func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobProgress, arg.Progress, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.SubjectID,
		&i.Payload,
		&i.Result,
		&i.Progress,
		&i.Error,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
