// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mastery_snapshot.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSnapshot = `-- name: InsertSnapshot :one

INSERT INTO mastery_snapshot (student_id, topic_id, mastery, attempts)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, topic_id, mastery, attempts, captured_at
`

type InsertSnapshotParams struct {
	StudentID string  `json:"studentId"`
	TopicID   string  `json:"topicId"`
	Mastery   float32 `json:"mastery"`
	Attempts  int32   `json:"attempts"`
}

// MasterySnapshot queries (D07) — contract 2-C08 (Dashboard timeline).
func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (MasterySnapshot, error) {
	row := q.db.QueryRow(ctx, insertSnapshot,
		arg.StudentID,
		arg.TopicID,
		arg.Mastery,
		arg.Attempts,
	)
	var i MasterySnapshot
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TopicID,
		&i.Mastery,
		&i.Attempts,
		&i.CapturedAt,
	)
	return i, err
}

const latestByStudent = `-- name: LatestByStudent :many
SELECT DISTINCT ON (topic_id) id, student_id, topic_id, mastery, attempts, captured_at
FROM mastery_snapshot
WHERE student_id = $1
ORDER BY topic_id, captured_at DESC, id DESC
`

// Most recent snapshot per topic for a student (current mastery state).
func (q *Queries) LatestByStudent(ctx context.Context, studentID string) ([]MasterySnapshot, error) {
	rows, err := q.db.Query(ctx, latestByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterySnapshot{}
	for rows.Next() {
		var i MasterySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TopicID,
			&i.Mastery,
			&i.Attempts,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByStudent = `-- name: ListSnapshotsByStudent :many
SELECT id, student_id, topic_id, mastery, attempts, captured_at FROM mastery_snapshot
WHERE student_id = $1
  AND ($2::timestamptz IS NULL OR captured_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR captured_at <= $3::timestamptz)
ORDER BY captured_at ASC, id ASC
`

type ListSnapshotsByStudentParams struct {
	StudentID string             `json:"studentId"`
	From      pgtype.Timestamptz `json:"from"`
	To        pgtype.Timestamptz `json:"to"`
}

// Range-filtered timeline for the dashboard. NULL range bounds are skipped, so
// omitting both returns the student's full history, oldest first for charting.
func (q *Queries) ListSnapshotsByStudent(ctx context.Context, arg ListSnapshotsByStudentParams) ([]MasterySnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByStudent, arg.StudentID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterySnapshot{}
	for rows.Next() {
		var i MasterySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TopicID,
			&i.Mastery,
			&i.Attempts,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
