// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: option.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createOption = `-- name: CreateOption :one
INSERT INTO option (question_id, text, "order")
VALUES ($1, $2, $3)
RETURNING id, question_id, text, "order"
`

type CreateOptionParams struct {
	QuestionID string `json:"questionId"`
	Text       string `json:"text"`
	Order      int32  `json:"order"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, createOption, arg.QuestionID, arg.Text, arg.Order)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.Order,
	)
	return i, err
}

const deleteOptionsByQuestion = `-- name: DeleteOptionsByQuestion :exec
DELETE FROM option
WHERE question_id = $1
`

func (q *Queries) DeleteOptionsByQuestion(ctx context.Context, questionID string) error {
	_, err := q.db.Exec(ctx, deleteOptionsByQuestion, questionID)
	return err
}

const listOptionsByQuestion = `-- name: ListOptionsByQuestion :many
SELECT id, question_id, text, "order" FROM option
WHERE question_id = $1
ORDER BY "order", id
`

func (q *Queries) ListOptionsByQuestion(ctx context.Context, questionID string) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByQuestionIDs = `-- name: ListOptionsByQuestionIDs :many
SELECT id, question_id, text, "order" FROM option
WHERE question_id = ANY($1::uuid[])
ORDER BY question_id, "order", id
`

func (q *Queries) ListOptionsByQuestionIDs(ctx context.Context, questionIds []uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByQuestionIDs, questionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
