// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent.sql

package store

import (
	"context"
)

const addCredential = `-- name: AddCredential :one
INSERT INTO credential (parent_id, credential_id, public_key, counter, is_backup)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parent_id, credential_id, public_key, counter, is_backup
`

type AddCredentialParams struct {
	ParentID     string `json:"parentId"`
	CredentialID []byte `json:"credentialId"`
	PublicKey    []byte `json:"publicKey"`
	Counter      int64  `json:"counter"`
	IsBackup     bool   `json:"isBackup"`
}

func (q *Queries) AddCredential(ctx context.Context, arg AddCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, addCredential,
		arg.ParentID,
		arg.CredentialID,
		arg.PublicKey,
		arg.Counter,
		arg.IsBackup,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.IsBackup,
	)
	return i, err
}

const createParent = `-- name: CreateParent :one

INSERT INTO parent (display_name, email)
VALUES ($1, $2)
RETURNING id, display_name, email, created_at
`

type CreateParentParams struct {
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
}

// Parent + Credential queries (D10) — contract C08.
func (q *Queries) CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, createParent, arg.DisplayName, arg.Email)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getParentByEmail = `-- name: GetParentByEmail :one
SELECT id, display_name, email, created_at FROM parent
WHERE email = $1
`

func (q *Queries) GetParentByEmail(ctx context.Context, email string) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByEmail, email)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentialsByParent = `-- name: ListCredentialsByParent :many
SELECT id, parent_id, credential_id, public_key, counter, is_backup FROM credential
WHERE parent_id = $1
`

func (q *Queries) ListCredentialsByParent(ctx context.Context, parentID string) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CredentialID,
			&i.PublicKey,
			&i.Counter,
			&i.IsBackup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialCounter = `-- name: UpdateCredentialCounter :one
UPDATE credential
SET counter = $2
WHERE credential_id = $1
RETURNING id, parent_id, credential_id, public_key, counter, is_backup
`

type UpdateCredentialCounterParams struct {
	CredentialID []byte `json:"credentialId"`
	Counter      int64  `json:"counter"`
}

func (q *Queries) UpdateCredentialCounter(ctx context.Context, arg UpdateCredentialCounterParams) (Credential, error) {
	row := q.db.QueryRow(ctx, updateCredentialCounter, arg.CredentialID, arg.Counter)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.IsBackup,
	)
	return i, err
}
