// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCredential(ctx context.Context, arg AddCredentialParams) (Credential, error)
	AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error)
	// Atomically claim the oldest runnable queued job and mark it processing.
	// FOR UPDATE SKIP LOCKED lets multiple workers run concurrently without contention.
	ClaimNextJob(ctx context.Context) (Job, error)
	// Mark a job ready and store its result payload.
	CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error)
	CountByStudent(ctx context.Context, studentID string) (int64, error)
	CountExamDefinitionsBySubject(ctx context.Context, subjectID string) (int64, error)
	CountQuestionsBySubject(ctx context.Context, subjectID string) (int64, error)
	CountQuestionsByTopic(ctx context.Context, topicID *string) (int64, error)
	CountSourcesBySubject(ctx context.Context, subjectID string) (int64, error)
	CountSubjects(ctx context.Context, archived *bool) (int64, error)
	CountTopicsBySubject(ctx context.Context, subjectID string) (int64, error)
	// ExamAttempt queries (D07, contract C06).
	// Supports the exam loop: start, fetch, submit (grade), history, cooldown lookup.
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (ExamAttempt, error)
	// File blob queries (D08) — contract 2-D08.
	CreateBlob(ctx context.Context, arg CreateBlobParams) (FileBlob, error)
	// Conversation + Message queries (D01) — contract 2-C01.
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateExamDefinition(ctx context.Context, arg CreateExamDefinitionParams) (ExamDefinition, error)
	// Guidance queries (D05) — contract 2-C07.
	CreateGuidance(ctx context.Context, arg CreateGuidanceParams) (Guidance, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error)
	// Parent + Credential queries (D10) — contract C08.
	CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error)
	// D05 — Question queries (matches §C05). Options live in D06.
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	// Subject queries (D01) — contract C01.
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	// D03 — Topic queries (sqlc)
	//
	// One file per table. Emits type-safe Go into internal/store (pgx/v5).
	// Matches CONTRACTS.md §C03.
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteBlob(ctx context.Context, id string) error
	DeleteExamDefinition(ctx context.Context, id string) error
	DeleteGuidance(ctx context.Context, id string) error
	DeleteOptionsByQuestion(ctx context.Context, questionID string) error
	DeleteQuestion(ctx context.Context, id string) error
	DeleteSource(ctx context.Context, id string) error
	DeleteSubject(ctx context.Context, id string) error
	DeleteTopic(ctx context.Context, id string) error
	// Job queue queries (D03) — contract 2-C03. Drives the 2-F06 worker.
	// Schedule a new job. run_after defaults to now() when NULL is passed.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	// Mark a job errored and store the failure message.
	FailJob(ctx context.Context, arg FailJobParams) (Job, error)
	GetAttempt(ctx context.Context, id string) (ExamAttempt, error)
	GetBlob(ctx context.Context, id string) (FileBlob, error)
	GetConversation(ctx context.Context, id string) (Conversation, error)
	GetExamDefinition(ctx context.Context, id string) (ExamDefinition, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetLastFailedForExam(ctx context.Context, arg GetLastFailedForExamParams) (ExamAttempt, error)
	GetParentByEmail(ctx context.Context, email string) (Parent, error)
	GetQuestion(ctx context.Context, id string) (Question, error)
	GetQuestionDraft(ctx context.Context, id string) (QuestionDraft, error)
	// Settings queries (D11) — contract C09. Single-row ('singleton') pattern.
	// Returns the singleton settings row.
	GetSettings(ctx context.Context) (Setting, error)
	GetSource(ctx context.Context, id string) (Source, error)
	// Student queries (D09) — contract C07.
	// Single-student Phase 1: return the one (newest) student profile.
	GetStudent(ctx context.Context) (Student, error)
	GetStudentByID(ctx context.Context, id string) (Student, error)
	// Fetch the guide for a (subject, topic). When sqlc.narg('topic_id') is NULL the
	// subject-level guide is returned.
	GetStudyGuide(ctx context.Context, arg GetStudyGuideParams) (StudyGuide, error)
	GetSubject(ctx context.Context, id string) (Subject, error)
	GetTopic(ctx context.Context, id string) (Topic, error)
	// TutorInstructions queries (D04) — contract 2-C06. One row per subject.
	GetTutorInstructionsBySubject(ctx context.Context, subjectID string) (TutorInstruction, error)
	// answer.sql — queries for the answer table (D08, contract C06).
	// InsertAnswers bulk-inserts all answers for an attempt in a single round trip
	// (pgx COPY). Submit grades every question and writes the whole set at once;
	// the unique(attempt_id, question_id) constraint guarantees at most one answer
	// per question per attempt.
	InsertAnswers(ctx context.Context, arg []InsertAnswersParams) (int64, error)
	// QuestionDraft queries (D06) — contract 2-C05.
	// Insert a single generated draft. Used in a batch loop for generation results.
	InsertQuestionDraft(ctx context.Context, arg InsertQuestionDraftParams) (QuestionDraft, error)
	// MasterySnapshot queries (D07) — contract 2-C08 (Dashboard timeline).
	InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (MasterySnapshot, error)
	// Most recent snapshot per topic for a student (current mastery state).
	LatestByStudent(ctx context.Context, studentID string) ([]MasterySnapshot, error)
	// ListAnswersByAttempt returns every answer recorded for an attempt.
	ListAnswersByAttempt(ctx context.Context, attemptID string) ([]Answer, error)
	ListByStudent(ctx context.Context, arg ListByStudentParams) ([]ExamAttempt, error)
	ListCredentialsByParent(ctx context.Context, parentID string) ([]Credential, error)
	// Eligible question bank for exam assembly (L04 / L08): enabled questions in the
	// subject, narrowed to a topic scope when provided. An empty scope array means
	// "whole subject" (no topic filter).
	ListEligibleForExam(ctx context.Context, arg ListEligibleForExamParams) ([]Question, error)
	ListExamDefinitionsBySubject(ctx context.Context, arg ListExamDefinitionsBySubjectParams) ([]ExamDefinition, error)
	// Optionally filtered by scope and/or subject. When a narg is NULL the
	// corresponding filter is skipped. Newest first.
	ListGuidance(ctx context.Context, arg ListGuidanceParams) ([]Guidance, error)
	// Optionally filtered by subject, newest first.
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListMessages(ctx context.Context, conversationID string) ([]Message, error)
	ListOptionsByQuestion(ctx context.Context, questionID string) ([]Option, error)
	ListOptionsByQuestionIDs(ctx context.Context, questionIds []uuid.UUID) ([]Option, error)
	// List drafts, optionally filtering by status. When sqlc.narg('status') is NULL
	// the filter is skipped and drafts of every status return, newest first.
	ListQuestionDrafts(ctx context.Context, status *string) ([]QuestionDraft, error)
	ListQuestionsBySubject(ctx context.Context, arg ListQuestionsBySubjectParams) ([]Question, error)
	ListQuestionsByTopic(ctx context.Context, arg ListQuestionsByTopicParams) ([]Question, error)
	// Range-filtered timeline for the dashboard. NULL range bounds are skipped, so
	// omitting both returns the student's full history, oldest first for charting.
	ListSnapshotsByStudent(ctx context.Context, arg ListSnapshotsByStudentParams) ([]MasterySnapshot, error)
	ListSourcesBySubject(ctx context.Context, arg ListSourcesBySubjectParams) ([]Source, error)
	// Paginated, optionally filtering by archived. When sqlc.narg('archived') is
	// NULL the filter is skipped and both archived and non-archived rows return.
	ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]Subject, error)
	ListTopicsBySubject(ctx context.Context, arg ListTopicsBySubjectParams) ([]Topic, error)
	MarkSubmitted(ctx context.Context, arg MarkSubmittedParams) (ExamAttempt, error)
	// Advance a draft through its review lifecycle (pending → approved/rejected).
	SetQuestionDraftStatus(ctx context.Context, arg SetQuestionDraftStatusParams) (QuestionDraft, error)
	UpdateCredentialCounter(ctx context.Context, arg UpdateCredentialCounterParams) (Credential, error)
	UpdateExamDefinition(ctx context.Context, arg UpdateExamDefinitionParams) (ExamDefinition, error)
	// Report incremental progress (0-100) while processing.
	UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (Job, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	// Partial update: NULL params leave the existing value untouched.
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error)
	// Inserts or updates the singleton settings row. NULL params fall back to the
	// spec defaults on insert and leave the existing value untouched on update.
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error)
	// Insert when id is NULL, otherwise update the existing row. Partial update:
	// NULL params leave the existing value untouched.
	UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error)
	// StudyGuide queries (D02) — contract 2-C02.
	// Inserts or replaces the guide for a (subject, topic) pair. topic_id NULL is the
	// subject-level guide. Two partial unique indexes back the conflict targets, so we
	// branch on whether topic_id is supplied.
	UpsertStudyGuide(ctx context.Context, arg UpsertStudyGuideParams) (StudyGuide, error)
	// Subject-level guide upsert (topic_id IS NULL), backed by study_guide_subject_idx.
	UpsertSubjectStudyGuide(ctx context.Context, arg UpsertSubjectStudyGuideParams) (StudyGuide, error)
	UpsertTutorInstructions(ctx context.Context, arg UpsertTutorInstructionsParams) (TutorInstruction, error)
}

var _ Querier = (*Queries)(nil)
