// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCredential(ctx context.Context, arg AddCredentialParams) (Credential, error)
	CountByStudent(ctx context.Context, studentID string) (int64, error)
	CountExamDefinitionsBySubject(ctx context.Context, subjectID string) (int64, error)
	CountQuestionsBySubject(ctx context.Context, subjectID string) (int64, error)
	CountQuestionsByTopic(ctx context.Context, topicID *string) (int64, error)
	CountSourcesBySubject(ctx context.Context, subjectID string) (int64, error)
	CountSubjects(ctx context.Context, archived *bool) (int64, error)
	CountTopicsBySubject(ctx context.Context, subjectID string) (int64, error)
	// ExamAttempt queries (D07, contract C06).
	// Supports the exam loop: start, fetch, submit (grade), history, cooldown lookup.
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (ExamAttempt, error)
	CreateExamDefinition(ctx context.Context, arg CreateExamDefinitionParams) (ExamDefinition, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error)
	// Parent + Credential queries (D10) — contract C08.
	CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error)
	// D05 — Question queries (matches §C05). Options live in D06.
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	// Subject queries (D01) — contract C01.
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	// D03 — Topic queries (sqlc)
	//
	// One file per table. Emits type-safe Go into internal/store (pgx/v5).
	// Matches CONTRACTS.md §C03.
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteExamDefinition(ctx context.Context, id string) error
	DeleteOptionsByQuestion(ctx context.Context, questionID string) error
	DeleteQuestion(ctx context.Context, id string) error
	DeleteSource(ctx context.Context, id string) error
	DeleteSubject(ctx context.Context, id string) error
	DeleteTopic(ctx context.Context, id string) error
	GetAttempt(ctx context.Context, id string) (ExamAttempt, error)
	GetExamDefinition(ctx context.Context, id string) (ExamDefinition, error)
	GetLastFailedForExam(ctx context.Context, arg GetLastFailedForExamParams) (ExamAttempt, error)
	GetParentByEmail(ctx context.Context, email string) (Parent, error)
	GetQuestion(ctx context.Context, id string) (Question, error)
	// Settings queries (D11) — contract C09. Single-row ('singleton') pattern.
	// Returns the singleton settings row.
	GetSettings(ctx context.Context) (Setting, error)
	GetSource(ctx context.Context, id string) (Source, error)
	// Student queries (D09) — contract C07.
	// Single-student Phase 1: return the one (newest) student profile.
	GetStudent(ctx context.Context) (Student, error)
	GetStudentByID(ctx context.Context, id string) (Student, error)
	GetSubject(ctx context.Context, id string) (Subject, error)
	GetTopic(ctx context.Context, id string) (Topic, error)
	// answer.sql — queries for the answer table (D08, contract C06).
	// InsertAnswers bulk-inserts all answers for an attempt in a single round trip
	// (pgx COPY). Submit grades every question and writes the whole set at once;
	// the unique(attempt_id, question_id) constraint guarantees at most one answer
	// per question per attempt.
	InsertAnswers(ctx context.Context, arg []InsertAnswersParams) (int64, error)
	// ListAnswersByAttempt returns every answer recorded for an attempt.
	ListAnswersByAttempt(ctx context.Context, attemptID string) ([]Answer, error)
	ListByStudent(ctx context.Context, arg ListByStudentParams) ([]ExamAttempt, error)
	ListCredentialsByParent(ctx context.Context, parentID string) ([]Credential, error)
	// Eligible question bank for exam assembly (L04 / L08): enabled questions in the
	// subject, narrowed to a topic scope when provided. An empty scope array means
	// "whole subject" (no topic filter).
	ListEligibleForExam(ctx context.Context, arg ListEligibleForExamParams) ([]Question, error)
	ListExamDefinitionsBySubject(ctx context.Context, arg ListExamDefinitionsBySubjectParams) ([]ExamDefinition, error)
	ListOptionsByQuestion(ctx context.Context, questionID string) ([]Option, error)
	ListOptionsByQuestionIDs(ctx context.Context, questionIds []uuid.UUID) ([]Option, error)
	ListQuestionsBySubject(ctx context.Context, arg ListQuestionsBySubjectParams) ([]Question, error)
	ListQuestionsByTopic(ctx context.Context, arg ListQuestionsByTopicParams) ([]Question, error)
	ListSourcesBySubject(ctx context.Context, arg ListSourcesBySubjectParams) ([]Source, error)
	// Paginated, optionally filtering by archived. When sqlc.narg('archived') is
	// NULL the filter is skipped and both archived and non-archived rows return.
	ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]Subject, error)
	ListTopicsBySubject(ctx context.Context, arg ListTopicsBySubjectParams) ([]Topic, error)
	MarkSubmitted(ctx context.Context, arg MarkSubmittedParams) (ExamAttempt, error)
	UpdateCredentialCounter(ctx context.Context, arg UpdateCredentialCounterParams) (Credential, error)
	UpdateExamDefinition(ctx context.Context, arg UpdateExamDefinitionParams) (ExamDefinition, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	// Partial update: NULL params leave the existing value untouched.
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error)
	// Inserts or updates the singleton settings row. NULL params fall back to the
	// spec defaults on insert and leave the existing value untouched on update.
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error)
	// Insert when id is NULL, otherwise update the existing row. Partial update:
	// NULL params leave the existing value untouched.
	UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error)
}

var _ Querier = (*Queries)(nil)
