// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countQuestionsBySubject = `-- name: CountQuestionsBySubject :one
SELECT count(*) FROM question
WHERE subject_id = $1
`

func (q *Queries) CountQuestionsBySubject(ctx context.Context, subjectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestionsByTopic = `-- name: CountQuestionsByTopic :one
SELECT count(*) FROM question
WHERE topic_id = $1
`

func (q *Queries) CountQuestionsByTopic(ctx context.Context, topicID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionsByTopic, topicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuestion = `-- name: CreateQuestion :one

INSERT INTO question (
    subject_id,
    topic_id,
    text,
    correct_option_id,
    difficulty,
    enabled
) VALUES (
    $1, $2, $3, $4, COALESCE($5, 'medium'), COALESCE($6, true)
)
RETURNING id, subject_id, topic_id, text, correct_option_id, difficulty, enabled, created_at
`

type CreateQuestionParams struct {
	SubjectID       string      `json:"subjectId"`
	TopicID         *string     `json:"topicId"`
	Text            string      `json:"text"`
	CorrectOptionID string      `json:"correctOptionId"`
	Difficulty      interface{} `json:"difficulty"`
	Enabled         interface{} `json:"enabled"`
}

// D05 — Question queries (matches §C05). Options live in D06.
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.SubjectID,
		arg.TopicID,
		arg.Text,
		arg.CorrectOptionID,
		arg.Difficulty,
		arg.Enabled,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Text,
		&i.CorrectOptionID,
		&i.Difficulty,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM question
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, subject_id, topic_id, text, correct_option_id, difficulty, enabled, created_at FROM question
WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Text,
		&i.CorrectOptionID,
		&i.Difficulty,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listEligibleForExam = `-- name: ListEligibleForExam :many
SELECT id, subject_id, topic_id, text, correct_option_id, difficulty, enabled, created_at FROM question
WHERE subject_id = $1
  AND enabled = true
  AND (
        cardinality($2::uuid[]) = 0
        OR topic_id = ANY($2::uuid[])
      )
ORDER BY created_at DESC, id
`

type ListEligibleForExamParams struct {
	SubjectID     string      `json:"subjectId"`
	ScopeTopicIds []uuid.UUID `json:"scopeTopicIds"`
}

// Eligible question bank for exam assembly (L04 / L08): enabled questions in the
// subject, narrowed to a topic scope when provided. An empty scope array means
// "whole subject" (no topic filter).
func (q *Queries) ListEligibleForExam(ctx context.Context, arg ListEligibleForExamParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listEligibleForExam, arg.SubjectID, arg.ScopeTopicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.TopicID,
			&i.Text,
			&i.CorrectOptionID,
			&i.Difficulty,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsBySubject = `-- name: ListQuestionsBySubject :many
SELECT id, subject_id, topic_id, text, correct_option_id, difficulty, enabled, created_at FROM question
WHERE subject_id = $1
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListQuestionsBySubjectParams struct {
	SubjectID string `json:"subjectId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListQuestionsBySubject(ctx context.Context, arg ListQuestionsBySubjectParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsBySubject, arg.SubjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.TopicID,
			&i.Text,
			&i.CorrectOptionID,
			&i.Difficulty,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByTopic = `-- name: ListQuestionsByTopic :many
SELECT id, subject_id, topic_id, text, correct_option_id, difficulty, enabled, created_at FROM question
WHERE topic_id = $1
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListQuestionsByTopicParams struct {
	TopicID *string `json:"topicId"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) ListQuestionsByTopic(ctx context.Context, arg ListQuestionsByTopicParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByTopic, arg.TopicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.TopicID,
			&i.Text,
			&i.CorrectOptionID,
			&i.Difficulty,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE question
SET
    topic_id          = COALESCE($1, topic_id),
    text              = COALESCE($2, text),
    correct_option_id = COALESCE($3, correct_option_id),
    difficulty        = COALESCE($4, difficulty),
    enabled           = COALESCE($5, enabled)
WHERE id = $6
RETURNING id, subject_id, topic_id, text, correct_option_id, difficulty, enabled, created_at
`

type UpdateQuestionParams struct {
	TopicID         *string `json:"topicId"`
	Text            *string `json:"text"`
	CorrectOptionID *string `json:"correctOptionId"`
	Difficulty      *string `json:"difficulty"`
	Enabled         *bool   `json:"enabled"`
	ID              string  `json:"id"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.TopicID,
		arg.Text,
		arg.CorrectOptionID,
		arg.Difficulty,
		arg.Enabled,
		arg.ID,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Text,
		&i.CorrectOptionID,
		&i.Difficulty,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
