// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question_draft.sql

package store

import (
	"context"
)

const getQuestionDraft = `-- name: GetQuestionDraft :one
SELECT id, subject_id, topic_id, text, options, correct_option_index, difficulty, status, created_at FROM question_draft
WHERE id = $1
`

func (q *Queries) GetQuestionDraft(ctx context.Context, id string) (QuestionDraft, error) {
	row := q.db.QueryRow(ctx, getQuestionDraft, id)
	var i QuestionDraft
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Text,
		&i.Options,
		&i.CorrectOptionIndex,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuestionDraft = `-- name: InsertQuestionDraft :one

INSERT INTO question_draft (subject_id, topic_id, text, options, correct_option_index, difficulty)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, subject_id, topic_id, text, options, correct_option_index, difficulty, status, created_at
`

type InsertQuestionDraftParams struct {
	SubjectID          string  `json:"subjectId"`
	TopicID            *string `json:"topicId"`
	Text               string  `json:"text"`
	Options            []byte  `json:"options"`
	CorrectOptionIndex int32   `json:"correctOptionIndex"`
	Difficulty         *string `json:"difficulty"`
}

// QuestionDraft queries (D06) — contract 2-C05.
// Insert a single generated draft. Used in a batch loop for generation results.
func (q *Queries) InsertQuestionDraft(ctx context.Context, arg InsertQuestionDraftParams) (QuestionDraft, error) {
	row := q.db.QueryRow(ctx, insertQuestionDraft,
		arg.SubjectID,
		arg.TopicID,
		arg.Text,
		arg.Options,
		arg.CorrectOptionIndex,
		arg.Difficulty,
	)
	var i QuestionDraft
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Text,
		&i.Options,
		&i.CorrectOptionIndex,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestionDrafts = `-- name: ListQuestionDrafts :many
SELECT id, subject_id, topic_id, text, options, correct_option_index, difficulty, status, created_at FROM question_draft
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY created_at DESC, id DESC
`

// List drafts, optionally filtering by status. When sqlc.narg('status') is NULL
// the filter is skipped and drafts of every status return, newest first.
func (q *Queries) ListQuestionDrafts(ctx context.Context, status *string) ([]QuestionDraft, error) {
	rows, err := q.db.Query(ctx, listQuestionDrafts, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionDraft{}
	for rows.Next() {
		var i QuestionDraft
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.TopicID,
			&i.Text,
			&i.Options,
			&i.CorrectOptionIndex,
			&i.Difficulty,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuestionDraftStatus = `-- name: SetQuestionDraftStatus :one
UPDATE question_draft
SET status = $2
WHERE id = $1
RETURNING id, subject_id, topic_id, text, options, correct_option_index, difficulty, status, created_at
`

type SetQuestionDraftStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

// Advance a draft through its review lifecycle (pending → approved/rejected).
func (q *Queries) SetQuestionDraftStatus(ctx context.Context, arg SetQuestionDraftStatusParams) (QuestionDraft, error) {
	row := q.db.QueryRow(ctx, setQuestionDraftStatus, arg.ID, arg.Status)
	var i QuestionDraft
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Text,
		&i.Options,
		&i.CorrectOptionIndex,
		&i.Difficulty,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
