// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSettings = `-- name: GetSettings :one

SELECT id, reward_rate_min_per_q, daily_cap_hours, default_exam_size, default_pass_bar, default_cooldown_min, knowledge_backend, difficulty_ramp FROM settings
WHERE id = 'singleton'
`

// Settings queries (D11) — contract C09. Single-row ('singleton') pattern.
// Returns the singleton settings row.
func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.RewardRateMinPerQ,
		&i.DailyCapHours,
		&i.DefaultExamSize,
		&i.DefaultPassBar,
		&i.DefaultCooldownMin,
		&i.KnowledgeBackend,
		&i.DifficultyRamp,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (
    id,
    reward_rate_min_per_q,
    daily_cap_hours,
    default_exam_size,
    default_pass_bar,
    default_cooldown_min,
    knowledge_backend,
    difficulty_ramp
)
VALUES (
    'singleton',
    COALESCE($1, 3),
    COALESCE($2, 3),
    COALESCE($3, 20),
    COALESCE($4, 70),
    COALESCE($5, 10),
    COALESCE($6, 'notebooklm'),
    COALESCE($7, false)
)
ON CONFLICT (id) DO UPDATE
SET
    reward_rate_min_per_q = COALESCE($1, settings.reward_rate_min_per_q),
    daily_cap_hours       = COALESCE($2, settings.daily_cap_hours),
    default_exam_size     = COALESCE($3, settings.default_exam_size),
    default_pass_bar      = COALESCE($4, settings.default_pass_bar),
    default_cooldown_min  = COALESCE($5, settings.default_cooldown_min),
    knowledge_backend     = COALESCE($6, settings.knowledge_backend),
    difficulty_ramp       = COALESCE($7, settings.difficulty_ramp)
RETURNING id, reward_rate_min_per_q, daily_cap_hours, default_exam_size, default_pass_bar, default_cooldown_min, knowledge_backend, difficulty_ramp
`

type UpsertSettingsParams struct {
	RewardRateMinPerQ  interface{} `json:"rewardRateMinPerQ"`
	DailyCapHours      interface{} `json:"dailyCapHours"`
	DefaultExamSize    interface{} `json:"defaultExamSize"`
	DefaultPassBar     interface{} `json:"defaultPassBar"`
	DefaultCooldownMin interface{} `json:"defaultCooldownMin"`
	KnowledgeBackend   interface{} `json:"knowledgeBackend"`
	DifficultyRamp     interface{} `json:"difficultyRamp"`
}

// Inserts or updates the singleton settings row. NULL params fall back to the
// spec defaults on insert and leave the existing value untouched on update.
func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSettings,
		arg.RewardRateMinPerQ,
		arg.DailyCapHours,
		arg.DefaultExamSize,
		arg.DefaultPassBar,
		arg.DefaultCooldownMin,
		arg.KnowledgeBackend,
		arg.DifficultyRamp,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.RewardRateMinPerQ,
		&i.DailyCapHours,
		&i.DefaultExamSize,
		&i.DefaultPassBar,
		&i.DefaultCooldownMin,
		&i.KnowledgeBackend,
		&i.DifficultyRamp,
	)
	return i, err
}
