// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source.sql

package store

import (
	"context"
)

const countSourcesBySubject = `-- name: CountSourcesBySubject :one
select count(*) from source
where subject_id = $1
`

func (q *Queries) CountSourcesBySubject(ctx context.Context, subjectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSourcesBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
insert into source (subject_id, type, title, status, file_ref, url, text)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, subject_id, type, title, status, file_ref, url, text, created_at
`

type CreateSourceParams struct {
	SubjectID string  `json:"subjectId"`
	Type      string  `json:"type"`
	Title     string  `json:"title"`
	Status    string  `json:"status"`
	FileRef   *string `json:"fileRef"`
	Url       *string `json:"url"`
	Text      *string `json:"text"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.SubjectID,
		arg.Type,
		arg.Title,
		arg.Status,
		arg.FileRef,
		arg.Url,
		arg.Text,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.FileRef,
		&i.Url,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
delete from source
where id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getSource = `-- name: GetSource :one
select id, subject_id, type, title, status, file_ref, url, text, created_at from source
where id = $1
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.FileRef,
		&i.Url,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listSourcesBySubject = `-- name: ListSourcesBySubject :many
select id, subject_id, type, title, status, file_ref, url, text, created_at from source
where subject_id = $1
order by created_at desc, id
limit $2 offset $3
`

type ListSourcesBySubjectParams struct {
	SubjectID string `json:"subjectId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListSourcesBySubject(ctx context.Context, arg ListSourcesBySubjectParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesBySubject, arg.SubjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Type,
			&i.Title,
			&i.Status,
			&i.FileRef,
			&i.Url,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
