// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student.sql

package store

import (
	"context"
)

const getStudent = `-- name: GetStudent :one

SELECT id, name, grade_level, avatar_url, notes, pin_hash, created_at FROM student
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Student queries (D09) — contract C07.
// Single-student Phase 1: return the one (newest) student profile.
func (q *Queries) GetStudent(ctx context.Context) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GradeLevel,
		&i.AvatarUrl,
		&i.Notes,
		&i.PinHash,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, name, grade_level, avatar_url, notes, pin_hash, created_at FROM student
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GradeLevel,
		&i.AvatarUrl,
		&i.Notes,
		&i.PinHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertStudent = `-- name: UpsertStudent :one
INSERT INTO student (id, name, grade_level, avatar_url, notes, pin_hash)
VALUES (
    COALESCE($1, gen_random_uuid()),
    COALESCE($2, ''),
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (id) DO UPDATE
SET
    name        = COALESCE($2, student.name),
    grade_level = COALESCE($3, student.grade_level),
    avatar_url  = COALESCE($4, student.avatar_url),
    notes       = COALESCE($5, student.notes),
    pin_hash    = COALESCE($6, student.pin_hash)
RETURNING id, name, grade_level, avatar_url, notes, pin_hash, created_at
`

type UpsertStudentParams struct {
	ID         interface{} `json:"id"`
	Name       interface{} `json:"name"`
	GradeLevel *string     `json:"gradeLevel"`
	AvatarUrl  *string     `json:"avatarUrl"`
	Notes      *string     `json:"notes"`
	PinHash    *string     `json:"pinHash"`
}

// Insert when id is NULL, otherwise update the existing row. Partial update:
// NULL params leave the existing value untouched.
func (q *Queries) UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, upsertStudent,
		arg.ID,
		arg.Name,
		arg.GradeLevel,
		arg.AvatarUrl,
		arg.Notes,
		arg.PinHash,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GradeLevel,
		&i.AvatarUrl,
		&i.Notes,
		&i.PinHash,
		&i.CreatedAt,
	)
	return i, err
}
