// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study_guide.sql

package store

import (
	"context"
)

const getStudyGuide = `-- name: GetStudyGuide :one
SELECT id, subject_id, topic_id, markdown, citations, generated_at FROM study_guide
WHERE subject_id = $1
  AND topic_id IS NOT DISTINCT FROM $2
`

type GetStudyGuideParams struct {
	SubjectID string  `json:"subjectId"`
	TopicID   *string `json:"topicId"`
}

// Fetch the guide for a (subject, topic). When sqlc.narg('topic_id') is NULL the
// subject-level guide is returned.
func (q *Queries) GetStudyGuide(ctx context.Context, arg GetStudyGuideParams) (StudyGuide, error) {
	row := q.db.QueryRow(ctx, getStudyGuide, arg.SubjectID, arg.TopicID)
	var i StudyGuide
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Markdown,
		&i.Citations,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertStudyGuide = `-- name: UpsertStudyGuide :one

INSERT INTO study_guide (subject_id, topic_id, markdown, citations)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (subject_id, topic_id) WHERE topic_id IS NOT NULL
DO UPDATE SET
    markdown     = EXCLUDED.markdown,
    citations    = EXCLUDED.citations,
    generated_at = now()
RETURNING id, subject_id, topic_id, markdown, citations, generated_at
`

type UpsertStudyGuideParams struct {
	SubjectID string  `json:"subjectId"`
	TopicID   *string `json:"topicId"`
	Markdown  string  `json:"markdown"`
	Citations []byte  `json:"citations"`
}

// StudyGuide queries (D02) — contract 2-C02.
// Inserts or replaces the guide for a (subject, topic) pair. topic_id NULL is the
// subject-level guide. Two partial unique indexes back the conflict targets, so we
// branch on whether topic_id is supplied.
func (q *Queries) UpsertStudyGuide(ctx context.Context, arg UpsertStudyGuideParams) (StudyGuide, error) {
	row := q.db.QueryRow(ctx, upsertStudyGuide,
		arg.SubjectID,
		arg.TopicID,
		arg.Markdown,
		arg.Citations,
	)
	var i StudyGuide
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Markdown,
		&i.Citations,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertSubjectStudyGuide = `-- name: UpsertSubjectStudyGuide :one
INSERT INTO study_guide (subject_id, topic_id, markdown, citations)
VALUES (
    $1,
    NULL,
    $2,
    $3
)
ON CONFLICT (subject_id) WHERE topic_id IS NULL
DO UPDATE SET
    markdown     = EXCLUDED.markdown,
    citations    = EXCLUDED.citations,
    generated_at = now()
RETURNING id, subject_id, topic_id, markdown, citations, generated_at
`

type UpsertSubjectStudyGuideParams struct {
	SubjectID string `json:"subjectId"`
	Markdown  string `json:"markdown"`
	Citations []byte `json:"citations"`
}

// Subject-level guide upsert (topic_id IS NULL), backed by study_guide_subject_idx.
func (q *Queries) UpsertSubjectStudyGuide(ctx context.Context, arg UpsertSubjectStudyGuideParams) (StudyGuide, error) {
	row := q.db.QueryRow(ctx, upsertSubjectStudyGuide, arg.SubjectID, arg.Markdown, arg.Citations)
	var i StudyGuide
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TopicID,
		&i.Markdown,
		&i.Citations,
		&i.GeneratedAt,
	)
	return i, err
}
