// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subject.sql

package store

import (
	"context"
)

const countSubjects = `-- name: CountSubjects :one
SELECT count(*) FROM subject
WHERE ($1::boolean IS NULL OR archived = $1::boolean)
`

func (q *Queries) CountSubjects(ctx context.Context, archived *bool) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjects, archived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubject = `-- name: CreateSubject :one

INSERT INTO subject (name, color, icon, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, icon, description, archived, created_at
`

type CreateSubjectParams struct {
	Name        string  `json:"name"`
	Color       *string `json:"color"`
	Icon        *string `json:"icon"`
	Description *string `json:"description"`
}

// Subject queries (D01) — contract C01.
func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.Description,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subject
WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const getSubject = `-- name: GetSubject :one
SELECT id, name, color, icon, description, archived, created_at FROM subject
WHERE id = $1
`

func (q *Queries) GetSubject(ctx context.Context, id string) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubject, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, color, icon, description, archived, created_at FROM subject
WHERE ($3::boolean IS NULL OR archived = $3::boolean)
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListSubjectsParams struct {
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
	Archived *bool `json:"archived"`
}

// Paginated, optionally filtering by archived. When sqlc.narg('archived') is
// NULL the filter is skipped and both archived and non-archived rows return.
func (q *Queries) ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects, arg.Limit, arg.Offset, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.Description,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subject
SET
    name        = COALESCE($1, name),
    color       = COALESCE($2, color),
    icon        = COALESCE($3, icon),
    description = COALESCE($4, description),
    archived    = COALESCE($5, archived)
WHERE id = $6
RETURNING id, name, color, icon, description, archived, created_at
`

type UpdateSubjectParams struct {
	Name        *string `json:"name"`
	Color       *string `json:"color"`
	Icon        *string `json:"icon"`
	Description *string `json:"description"`
	Archived    *bool   `json:"archived"`
	ID          string  `json:"id"`
}

// Partial update: NULL params leave the existing value untouched.
func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.Description,
		arg.Archived,
		arg.ID,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}
