// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: syllabus.sql

package store

import (
	"context"
)

const createSyllabus = `-- name: CreateSyllabus :one

INSERT INTO syllabus (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at
`

type CreateSyllabusParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

// Syllabus queries — the curriculum grouping above subjects (e.g. "Class V").
func (q *Queries) CreateSyllabus(ctx context.Context, arg CreateSyllabusParams) (Syllabus, error) {
	row := q.db.QueryRow(ctx, createSyllabus, arg.Name, arg.Description)
	var i Syllabus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSyllabus = `-- name: DeleteSyllabus :exec
DELETE FROM syllabus
WHERE id = $1
`

// Subjects referencing the syllabus are un-grouped via ON DELETE SET NULL.
func (q *Queries) DeleteSyllabus(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSyllabus, id)
	return err
}

const getSyllabus = `-- name: GetSyllabus :one
SELECT id, name, description, created_at FROM syllabus
WHERE id = $1
`

func (q *Queries) GetSyllabus(ctx context.Context, id string) (Syllabus, error) {
	row := q.db.QueryRow(ctx, getSyllabus, id)
	var i Syllabus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listSyllabuses = `-- name: ListSyllabuses :many
SELECT id, name, description, created_at FROM syllabus
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListSyllabuses(ctx context.Context) ([]Syllabus, error) {
	rows, err := q.db.Query(ctx, listSyllabuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Syllabus{}
	for rows.Next() {
		var i Syllabus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyllabus = `-- name: UpdateSyllabus :one
UPDATE syllabus
SET
    name        = COALESCE($1, name),
    description = COALESCE($2, description)
WHERE id = $3
RETURNING id, name, description, created_at
`

type UpdateSyllabusParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	ID          string  `json:"id"`
}

// Partial update: NULL params leave the existing value untouched.
func (q *Queries) UpdateSyllabus(ctx context.Context, arg UpdateSyllabusParams) (Syllabus, error) {
	row := q.db.QueryRow(ctx, updateSyllabus, arg.Name, arg.Description, arg.ID)
	var i Syllabus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
