// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package store

import (
	"context"
)

const countTopicsBySubject = `-- name: CountTopicsBySubject :one
SELECT count(*) FROM topic
WHERE subject_id = $1
`

func (q *Queries) CountTopicsBySubject(ctx context.Context, subjectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTopicsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTopic = `-- name: CreateTopic :one

INSERT INTO topic (
    subject_id,
    name,
    source_id,
    page_start,
    page_end,
    "order",
    active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE($7, true)
)
RETURNING id, subject_id, name, source_id, page_start, page_end, "order", active
`

type CreateTopicParams struct {
	SubjectID string      `json:"subjectId"`
	Name      string      `json:"name"`
	SourceID  *string     `json:"sourceId"`
	PageStart *int32      `json:"pageStart"`
	PageEnd   *int32      `json:"pageEnd"`
	SortOrder int32       `json:"sortOrder"`
	Active    interface{} `json:"active"`
}

// D03 — Topic queries (sqlc)
//
// One file per table. Emits type-safe Go into internal/store (pgx/v5).
// Matches CONTRACTS.md §C03.
func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.SubjectID,
		arg.Name,
		arg.SourceID,
		arg.PageStart,
		arg.PageEnd,
		arg.SortOrder,
		arg.Active,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.SourceID,
		&i.PageStart,
		&i.PageEnd,
		&i.Order,
		&i.Active,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topic
WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getTopic = `-- name: GetTopic :one
SELECT id, subject_id, name, source_id, page_start, page_end, "order", active FROM topic
WHERE id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id string) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.SourceID,
		&i.PageStart,
		&i.PageEnd,
		&i.Order,
		&i.Active,
	)
	return i, err
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT id, subject_id, name, source_id, page_start, page_end, "order", active FROM topic
WHERE subject_id = $1
ORDER BY "order" ASC, name ASC
LIMIT $3 OFFSET $2
`

type ListTopicsBySubjectParams struct {
	SubjectID  string `json:"subjectId"`
	PageOffset int32  `json:"pageOffset"`
	PageLimit  int32  `json:"pageLimit"`
}

func (q *Queries) ListTopicsBySubject(ctx context.Context, arg ListTopicsBySubjectParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsBySubject, arg.SubjectID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.SourceID,
			&i.PageStart,
			&i.PageEnd,
			&i.Order,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topic
SET
    name       = COALESCE($1, name),
    source_id  = CASE WHEN $2::boolean THEN $3 ELSE source_id END,
    page_start = CASE WHEN $4::boolean THEN $5 ELSE page_start END,
    page_end   = CASE WHEN $6::boolean THEN $7 ELSE page_end END,
    "order"    = COALESCE($8, "order"),
    active     = COALESCE($9, active)
WHERE id = $10
RETURNING id, subject_id, name, source_id, page_start, page_end, "order", active
`

type UpdateTopicParams struct {
	Name         *string `json:"name"`
	SetSourceID  bool    `json:"setSourceId"`
	SourceID     *string `json:"sourceId"`
	SetPageStart bool    `json:"setPageStart"`
	PageStart    *int32  `json:"pageStart"`
	SetPageEnd   bool    `json:"setPageEnd"`
	PageEnd      *int32  `json:"pageEnd"`
	SortOrder    *int32  `json:"sortOrder"`
	Active       *bool   `json:"active"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic,
		arg.Name,
		arg.SetSourceID,
		arg.SourceID,
		arg.SetPageStart,
		arg.PageStart,
		arg.SetPageEnd,
		arg.PageEnd,
		arg.SortOrder,
		arg.Active,
		arg.ID,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.SourceID,
		&i.PageStart,
		&i.PageEnd,
		&i.Order,
		&i.Active,
	)
	return i, err
}
