// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tutor_instructions.sql

package store

import (
	"context"
)

const getTutorInstructionsBySubject = `-- name: GetTutorInstructionsBySubject :one

SELECT subject_id, custom_instructions, tone, target_language, difficulty, created_at, updated_at FROM tutor_instructions
WHERE subject_id = $1
`

// TutorInstructions queries (D04) — contract 2-C06. One row per subject.
func (q *Queries) GetTutorInstructionsBySubject(ctx context.Context, subjectID string) (TutorInstruction, error) {
	row := q.db.QueryRow(ctx, getTutorInstructionsBySubject, subjectID)
	var i TutorInstruction
	err := row.Scan(
		&i.SubjectID,
		&i.CustomInstructions,
		&i.Tone,
		&i.TargetLanguage,
		&i.Difficulty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTutorInstructions = `-- name: UpsertTutorInstructions :one
INSERT INTO tutor_instructions (subject_id, custom_instructions, tone, target_language, difficulty)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (subject_id) DO UPDATE
SET
    custom_instructions = EXCLUDED.custom_instructions,
    tone                = EXCLUDED.tone,
    target_language     = EXCLUDED.target_language,
    difficulty          = EXCLUDED.difficulty,
    updated_at          = now()
RETURNING subject_id, custom_instructions, tone, target_language, difficulty, created_at, updated_at
`

type UpsertTutorInstructionsParams struct {
	SubjectID          string  `json:"subjectId"`
	CustomInstructions string  `json:"customInstructions"`
	Tone               *string `json:"tone"`
	TargetLanguage     *string `json:"targetLanguage"`
	Difficulty         *string `json:"difficulty"`
}

func (q *Queries) UpsertTutorInstructions(ctx context.Context, arg UpsertTutorInstructionsParams) (TutorInstruction, error) {
	row := q.db.QueryRow(ctx, upsertTutorInstructions,
		arg.SubjectID,
		arg.CustomInstructions,
		arg.Tone,
		arg.TargetLanguage,
		arg.Difficulty,
	)
	var i TutorInstruction
	err := row.Scan(
		&i.SubjectID,
		&i.CustomInstructions,
		&i.Tone,
		&i.TargetLanguage,
		&i.Difficulty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
