/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subjects */
        get: operations["listSubjects"];
        put?: never;
        /** Create a subject */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a subject */
        get: operations["getSubject"];
        /** Update a subject (partial) */
        put: operations["updateSubject"];
        post?: never;
        /** Delete a subject */
        delete: operations["deleteSubject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sources for a subject */
        get: operations["listSources"];
        put?: never;
        /** Create a source */
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a source */
        get: operations["getSource"];
        put?: never;
        post?: never;
        /** Delete a source */
        delete: operations["deleteSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List topics for a subject */
        get: operations["listTopics"];
        put?: never;
        /** Create a topic */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a topic */
        get: operations["getTopic"];
        /** Update a topic (partial) */
        put: operations["updateTopic"];
        post?: never;
        /** Delete a topic */
        delete: operations["deleteTopic"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exam definitions for a subject */
        get: operations["listExamDefinitions"];
        put?: never;
        /** Create an exam definition */
        post: operations["createExamDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get an exam definition */
        get: operations["getExamDefinition"];
        /** Update an exam definition (partial) */
        put: operations["updateExamDefinition"];
        post?: never;
        /** Delete an exam definition */
        delete: operations["deleteExamDefinition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List questions for a subject / topic */
        get: operations["listQuestions"];
        put?: never;
        /** Create a question */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a question */
        get: operations["getQuestion"];
        /** Update a question (partial) */
        put: operations["updateQuestion"];
        post?: never;
        /** Delete a question */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the student profile */
        get: operations["getStudent"];
        /** Update the student profile (partial) */
        put: operations["updateStudent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the application settings singleton */
        get: operations["getSettings"];
        /** Update settings (partial) */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exam attempts for a student */
        get: operations["listAttempts"];
        put?: never;
        /**
         * Start a new exam attempt
         * @description Assembles the exam and persists an in_progress attempt, returning the attempt plus the delivered questions (without the answer key).
         */
        post: operations["startAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get an in-progress attempt (no answers revealed) */
        get: operations["getAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit answers and grade the attempt
         * @description Grades the attempt server-side, persists the graded result, and returns the graded attempt plus the emitted ScoreEvent (the Phase 3 seam).
         */
        post: operations["submitAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get the graded result of an attempt (answers revealed) */
        get: operations["getAttemptResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parent WebAuthn registration ceremony (begin/finish)
         * @description Drives the parent WebAuthn registration ceremony. The opaque ceremony payload (begin options or the authenticator response) is passed through to go-webauthn. On finish, a Session is returned and the session cookie is set.
         */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parent WebAuthn login ceremony (begin/finish)
         * @description Drives the parent WebAuthn authentication ceremony. The opaque ceremony payload is passed through to go-webauthn. On finish, a Session is returned and the session cookie is set.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Student sign-in
         * @description Signs a student in (optionally with a PIN) and sets the session cookie.
         */
        post: operations["authStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a student's mastery, streak, and attempt history */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Lifecycle state of an exam attempt.
         * @enum {string}
         */
        AttemptStatus: "in_progress" | "submitted";
        /** @description A single answer within an attempt. selectedOptionId is absent when the student left the question unanswered; correct is populated only after server-side grading. */
        Answer: {
            /** @description The question this answer responds to. */
            questionId: string;
            /** @description The option the student selected, if any. */
            selectedOptionId?: string;
            /** @description Whether the selected option was correct (set on grading). */
            correct?: boolean;
        };
        /** @description Per-topic correct/total breakdown for an attempt. Canonical definition; ScoreEvent references this same shape. */
        PerTopicScore: {
            /** @description The topic these counts belong to. */
            topicId: string;
            /** @description Number of correctly answered questions for this topic. */
            correct: number;
            /** @description Total number of questions for this topic in the attempt. */
            total: number;
        };
        /** @description A student's attempt at an exam definition. Created in_progress with the assembled questionIds; graded fields (scorePct, passed, perTopic, cooldownUntil, submittedAt) are populated after submission. */
        ExamAttempt: {
            /** @description Unique attempt id. */
            id: string;
            /** @description The exam definition this attempt is for. */
            examDefinitionId: string;
            /** @description The student taking the exam. */
            studentId: string;
            /**
             * @description Current lifecycle state.
             * @default in_progress
             */
            status: components["schemas"]["AttemptStatus"];
            /** @description The assembled question ids, in delivery order. */
            questionIds: string[];
            /**
             * @description The student's answers; empty until questions are answered.
             * @default []
             */
            answers: components["schemas"]["Answer"][];
            /** @description Overall score percentage (0–100); present once graded. */
            scorePct?: number;
            /** @description Whether the attempt met the exam pass bar; present once graded. */
            passed?: boolean;
            /** @description Per-topic breakdown; present once graded. */
            perTopic?: components["schemas"]["PerTopicScore"][];
            /**
             * Format: date-time
             * @description RFC 3339 timestamp until which a new attempt is blocked after a failed attempt; absent when there is no active cooldown.
             */
            cooldownUntil?: string;
            /**
             * Format: date-time
             * @description When the attempt was started.
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description When the attempt was submitted; absent while in_progress.
             */
            submittedAt?: string;
        };
        /** @description Request body to start a new exam attempt. */
        StartAttempt: {
            /** @description The exam definition to attempt. */
            examDefinitionId: string;
            /** @description The student starting the attempt. */
            studentId: string;
        };
        /** @description Request body to submit answers for grading. */
        SubmitAttempt: {
            /** @description The submitted answers, one entry per answered question. */
            answers: {
                /** @description The question being answered. */
                questionId: string;
                /** @description The selected option id. */
                selectedOptionId: string;
            }[];
        };
        /** @description A paginated page of exam attempts. */
        PageOfExamAttempt: {
            items: components["schemas"]["ExamAttempt"][];
            /** @description Total number of attempts matching the query. */
            total: number;
            /** @description 1-based page number. */
            page: number;
            /** @description Number of items per page. */
            pageSize: number;
        };
        /** @description A parent/guardian account, authenticated via WebAuthn (FIDO2). */
        Parent: {
            /** @description Unique parent id (UUID/cuid). */
            id: string;
            /** @description Human-readable name shown in the UI. */
            displayName: string;
            /**
             * Format: email
             * @description Parent email address (also the WebAuthn user name).
             */
            email: string;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp.
             */
            createdAt: string;
        };
        /** @description A registered WebAuthn (FIDO2) credential belonging to a parent. Stores the public key + signature counter used to verify assertions. */
        Credential: {
            /** @description Unique credential record id (UUID/cuid). */
            id: string;
            /** @description Id of the owning Parent. */
            parentId: string;
            /** @description Base64url-encoded WebAuthn credential id. */
            credentialId: string;
            /** @description Base64url-encoded COSE public key. */
            publicKey: string;
            /**
             * Format: int64
             * @description Signature counter, used to detect cloned authenticators.
             */
            counter: number;
            /**
             * @description Whether the authenticator is backup-eligible / a backup device.
             * @default false
             */
            isBackup: boolean;
        };
        /** @description Body that starts the parent WebAuthn registration ceremony. The server replies with opaque registration options (handled by go-webauthn). */
        RegisterBegin: {
            /** @description Human-readable name for the new parent account. */
            displayName: string;
            /**
             * Format: email
             * @description Parent email address (the WebAuthn user name).
             */
            email: string;
        };
        /** @description The active session identity returned after a successful auth ceremony. Mirrors what the server stores behind the sr_session cookie. */
        Session: {
            /**
             * @description Whether the session belongs to a parent or a student.
             * @enum {string}
             */
            role: "parent" | "student";
            /** @description Id of the authenticated parent or student. */
            id: string;
        };
        /** @description Free-form WebAuthn ceremony payload (registration/authentication options or the authenticator's response). Opaque — the structure is owned by the WebAuthn libraries, not this contract. */
        WebAuthnCeremony: {
            [key: string]: unknown;
        };
        /**
         * @description Machine-readable error category. Maps to the matching HTTP status: VALIDATION->422/400, NOT_FOUND->404, UNAUTHORIZED->401, CONFLICT->409, INTERNAL->500.
         * @enum {string}
         */
        Code: "VALIDATION" | "NOT_FOUND" | "UNAUTHORIZED" | "CONFLICT" | "INTERNAL";
        /** @description RFC 7807-style problem detail returned for any error response. The HTTP status of the response matches the `status` field and the `code` category. */
        Problem: {
            /** @description A URI reference identifying the problem type. May be the literal "about:blank" when no specific type is defined. */
            type: string;
            /** @description A short, human-readable summary of the problem type. */
            title: string;
            /** @description The HTTP status code for this occurrence of the problem. */
            status: number;
            /** @description A human-readable explanation specific to this occurrence. */
            detail?: string;
            code: components["schemas"]["Code"];
        };
        /**
         * @description Kind of exam. `gate` exams are the everyday internet-time gate; `formal` exams are heavier graded assessments.
         * @enum {string}
         */
        ExamType: "gate" | "formal";
        /**
         * @description How earned internet time relates to the score. `flat` grants the full time for the exam size on a pass; `scaled` multiplies by the score%.
         * @enum {string}
         */
        RewardStyle: "flat" | "scaled";
        /** @description A parent-configured exam template for a subject. */
        ExamDefinition: {
            /** @description Stable identifier (UUID/cuid). */
            id: string;
            /** @description The subject this exam template belongs to. */
            subjectId: string;
            /** @description Human-readable name for the exam template. */
            name: string;
            /** @default gate */
            type: components["schemas"]["ExamType"];
            /**
             * @description Topic ids the exam draws from. An empty array means the whole subject.
             * @default []
             */
            scopeTopicIds: string[];
            /**
             * @description Number of questions in the exam.
             * @default 20
             */
            size: number;
            /**
             * @description Minimum score percentage required to pass.
             * @default 70
             */
            passBar: number;
            /**
             * @description Minutes a student must wait after a failed attempt.
             * @default 10
             */
            cooldownMin: number;
            /** @default flat */
            rewardStyle: components["schemas"]["RewardStyle"];
            /**
             * Format: date-time
             * @description When the exam template was created (RFC 3339).
             */
            createdAt: string;
        };
        /** @description Request body to create an ExamDefinition. The server assigns `id` and `createdAt` and applies the spec §10 defaults for any omitted field. */
        CreateExamDefinition: {
            /** @description The subject this exam template belongs to. */
            subjectId: string;
            /** @description Human-readable name for the exam template. */
            name: string;
            /** @default gate */
            type: components["schemas"]["ExamType"];
            /**
             * @description Topic ids the exam draws from. An empty array (the default) means the whole subject.
             * @default []
             */
            scopeTopicIds: string[];
            /**
             * @description Number of questions in the exam.
             * @default 20
             */
            size: number;
            /**
             * @description Minimum score percentage required to pass.
             * @default 70
             */
            passBar: number;
            /**
             * @description Minutes a student must wait after a failed attempt.
             * @default 10
             */
            cooldownMin: number;
            /** @default flat */
            rewardStyle: components["schemas"]["RewardStyle"];
        };
        /** @description A page of ExamDefinition results. */
        PageOfExamDefinition: {
            items: components["schemas"]["ExamDefinition"][];
            /** @description Total number of matching exam definitions. */
            total: number;
            /** @description 1-based page number. */
            page: number;
            /** @description Number of items per page. */
            pageSize: number;
        };
        /**
         * @description Relative difficulty of a question.
         * @enum {string}
         */
        Difficulty: "easy" | "medium" | "hard";
        /** @description A single multiple-choice answer option. The id is server-assigned. */
        Option: {
            /** @description Server-assigned identifier for this option (unique within a question). */
            id: string;
            /** @description The option's display text. */
            text: string;
        };
        /** @description A multiple-choice question with its answer key. This is the parent-facing (authoring) shape; the student receives DeliveredQuestion, which omits correctOptionId. */
        Question: {
            /** @description Unique question identifier. */
            id: string;
            /** @description Subject this question belongs to. */
            subjectId: string;
            /** @description Optional topic this question is scoped to. */
            topicId?: string;
            /** @description The question prompt. */
            text: string;
            /** @description The answer options. At least four are required. */
            options: components["schemas"]["Option"][];
            /** @description The id of the option that is correct (must match an option's id). */
            correctOptionId: string;
            /** @default medium */
            difficulty: components["schemas"]["Difficulty"];
            /**
             * @description Whether this question is eligible for selection into exams.
             * @default true
             */
            enabled: boolean;
        };
        /** @description Payload to author a new question. Options are supplied as plain texts and the correct one is identified by its index; the server assigns Option ids and resolves correctOptionId from correctOptionIndex. */
        CreateQuestion: {
            /** @description Subject this question belongs to. */
            subjectId: string;
            /** @description Optional topic this question is scoped to. */
            topicId?: string;
            /** @description The question prompt. */
            text: string;
            /** @description The answer option texts. At least four are required. */
            options: {
                /** @description The option's display text. */
                text: string;
            }[];
            /** @description Zero-based index into options identifying the correct answer. */
            correctOptionIndex: number;
            difficulty?: components["schemas"]["Difficulty"];
        };
        /** @description A question as delivered to the student during an exam — identical to Question but WITHOUT correctOptionId, so the answer key never leaves the server. Grading is performed server-side. */
        DeliveredQuestion: {
            /** @description Unique question identifier. */
            id: string;
            /** @description Subject this question belongs to. */
            subjectId: string;
            /** @description Optional topic this question is scoped to. */
            topicId?: string;
            /** @description The question prompt. */
            text: string;
            /** @description The answer options. At least four are required. */
            options: components["schemas"]["Option"][];
            /** @default medium */
            difficulty: components["schemas"]["Difficulty"];
            /**
             * @description Whether this question is eligible for selection into exams.
             * @default true
             */
            enabled: boolean;
        };
        /** @description A paginated page of questions. */
        PageOfQuestion: {
            items: components["schemas"]["Question"][];
            /** @description Total number of questions matching the query. */
            total: number;
            /** @description 1-based page number. */
            page: number;
            /** @description Number of items per page. */
            pageSize: number;
        };
        /** @description Immutable record of a single graded exam outcome. Emitted by Phase 1 on exam submission and consumed only by the Phase 3 Guardian. Carries the score and per-topic breakdown but no reward/minutes/time fields, which are Guardian-only. */
        ScoreEvent: {
            /** @description ID of the ExamAttempt (C06) this score came from. */
            attemptId: string;
            /** @description ID of the Student (C07) who took the exam. */
            studentId: string;
            /** @description ID of the Subject (C01) the exam belongs to. */
            subjectId: string;
            /** @description ID of the ExamDefinition (C04) that produced the attempt. */
            examDefinitionId: string;
            /** @description Topic IDs the exam was scoped to. Empty array means the whole subject (mirrors ExamDefinition.scopeTopicIds). */
            scopeTopicIds: string[];
            /** @description Number of questions in the attempt. */
            size: number;
            /** @description Final score as a whole percentage (0–100). */
            scorePct: number;
            /** @description Whether the attempt met the exam's pass bar. */
            passed: boolean;
            /** @description Per-topic correct/total breakdown for the attempt. */
            perTopic: components["schemas"]["PerTopicScore"][];
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of when the score was recorded.
             */
            timestamp: string;
        };
        /**
         * @description The swappable knowledge backend used by the AI tutor / ingestion (Phase 2). NotebookLM is the default; Gemini is the direct alternative.
         * @enum {string}
         */
        KnowledgeBackend: "notebooklm" | "gemini";
        /** @description The application settings singleton. Holds the spec defaults that gate exam creation plus the Guardian-side reward knobs (stored now, used in Phase 3). L10 ResolveSettings fills any missing field from these same defaults at runtime. */
        Settings: {
            /** @description Identifier of the settings singleton row. */
            id: string;
            /**
             * @description Guardian-side: minutes of earned time per correct question. Stored now, unused until Phase 3.
             * @default 3
             */
            rewardRateMinPerQ: number;
            /**
             * @description Guardian-side: maximum hours of earned time per day. Stored now, unused until Phase 3.
             * @default 3
             */
            dailyCapHours: number;
            /**
             * @description Default number of questions for a new exam definition.
             * @default 20
             */
            defaultExamSize: number;
            /**
             * @description Default pass threshold (percent) for a new exam definition.
             * @default 70
             */
            defaultPassBar: number;
            /**
             * @description Default cooldown (minutes) after a failed attempt.
             * @default 10
             */
            defaultCooldownMin: number;
            /**
             * @description The selected knowledge backend.
             * @default notebooklm
             */
            knowledgeBackend: components["schemas"]["KnowledgeBackend"];
            /**
             * @description Whether exam assembly ramps difficulty (easy -> hard) across the delivered questions.
             * @default false
             */
            difficultyRamp: boolean;
        };
        /**
         * @description The kind of study source.
         * @enum {string}
         */
        SourceType: "file" | "notebooklm" | "text";
        /**
         * @description Processing state of a source. Phase 1 sources are created `ready`; `processing` is reserved for Phase 2 async ingestion/OCR.
         * @enum {string}
         */
        SourceStatus: "processing" | "ready";
        /** @description A study source attached to a subject. */
        Source: {
            /** @description Unique source id (UUID/cuid). */
            id: string;
            /** @description Id of the subject this source belongs to. */
            subjectId: string;
            type: components["schemas"]["SourceType"];
            /** @description Human-readable title for the source. */
            title: string;
            /** @default ready */
            status: components["schemas"]["SourceStatus"];
            /** @description Storage reference for a `file` source (set only for files). */
            fileRef?: string;
            /** @description URL for a `notebooklm` source. */
            url?: string;
            /** @description Inline content for a `text` source. */
            text?: string;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp.
             */
            createdAt: string;
        };
        /** @description Payload to create a new source. Server assigns id/status/createdAt. */
        CreateSource: {
            /** @description Id of the subject this source belongs to. */
            subjectId: string;
            type: components["schemas"]["SourceType"];
            /** @description Human-readable title for the source. */
            title: string;
            /** @description Storage reference for a `file` source. */
            fileRef?: string;
            /** @description URL for a `notebooklm` source. */
            url?: string;
            /** @description Inline content for a `text` source. */
            text?: string;
        };
        /** @description A page of sources (Page<Source>). */
        PageOfSource: {
            items: components["schemas"]["Source"][];
            /** @description Total number of sources matching the query. */
            total: number;
            /** @description 1-based page number. */
            page: number;
            /** @description Number of items per page. */
            pageSize: number;
        };
        /** @description A learner profile. Created by the parent during setup and used as the identity the student signs in as for exams. */
        Student: {
            /** @description Server-assigned unique identifier (UUID/cuid). */
            id: string;
            /** @description The student's display name. */
            name: string;
            /** @description Optional grade / year level (free-form, e.g. "Grade 7"). */
            gradeLevel?: string;
            /** @description Optional URL to an avatar image. */
            avatarUrl?: string;
            /** @description Optional free-form notes the parent keeps about the student. */
            notes?: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of when the student was created.
             */
            createdAt: string;
        };
        /** @description Request body to create (or, in Phase 1, update via PUT) a student profile. The server assigns id and createdAt. */
        CreateStudent: {
            /** @description The student's display name. */
            name: string;
            /** @description Optional grade / year level (free-form, e.g. "Grade 7"). */
            gradeLevel?: string;
            /** @description Optional URL to an avatar image. */
            avatarUrl?: string;
            /** @description Optional free-form notes the parent keeps about the student. */
            notes?: string;
        };
        /** @description A unit of study a parent configures (e.g. "Algebra I"). */
        Subject: {
            /** @description Server-assigned unique identifier (UUID/cuid). */
            id: string;
            /** @description Human-readable subject name. */
            name: string;
            /** @description Optional display color (e.g. hex token) for the subject. */
            color?: string;
            /** @description Optional icon identifier for the subject. */
            icon?: string;
            /** @description Optional longer description of the subject. */
            description?: string;
            /**
             * @description Whether the subject is archived (hidden from active lists).
             * @default false
             */
            archived: boolean;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp.
             */
            createdAt: string;
        };
        /** @description Request body to create a Subject; server assigns id/createdAt and defaults archived=false. */
        CreateSubject: {
            /** @description Human-readable subject name. */
            name: string;
            /** @description Optional display color (e.g. hex token) for the subject. */
            color?: string;
            /** @description Optional icon identifier for the subject. */
            icon?: string;
            /** @description Optional longer description of the subject. */
            description?: string;
        };
        /** @description A single page of Subject results (Page<Subject> per the common pagination pattern). */
        PageOfSubject: {
            /** @description The Subjects in this page. */
            items: components["schemas"]["Subject"][];
            /** @description Total number of Subjects matching the query across all pages. */
            total: number;
            /** @description 1-based page number of this result. */
            page: number;
            /** @description Maximum number of items per page. */
            pageSize: number;
        };
        /** @description A unit of study within a subject. May optionally point at a source and a page range. `order` controls syllabus position; `active` toggles whether the topic is in scope for exams. */
        Topic: {
            /** @description Unique topic identifier (UUID/cuid). */
            id: string;
            /** @description Identifier of the owning subject. */
            subjectId: string;
            /** @description Human-readable topic name. */
            name: string;
            /** @description Optional identifier of the source this topic is drawn from. */
            sourceId?: string;
            /**
             * Format: int32
             * @description Optional first page of the topic within its source.
             */
            pageStart?: number;
            /**
             * Format: int32
             * @description Optional last page of the topic within its source. If both pages are present, pageEnd must be >= pageStart.
             */
            pageEnd?: number;
            /**
             * Format: int32
             * @description Position of the topic in the subject's syllabus.
             */
            order: number;
            /**
             * @description Whether the topic is active (in scope for exams).
             * @default true
             */
            active: boolean;
        };
        /** @description Request body for creating a topic. Server assigns id and defaults. */
        CreateTopic: {
            /** @description Identifier of the owning subject. */
            subjectId: string;
            /** @description Human-readable topic name. */
            name: string;
            /** @description Optional identifier of the source this topic is drawn from. */
            sourceId?: string;
            /**
             * Format: int32
             * @description Optional first page of the topic within its source.
             */
            pageStart?: number;
            /**
             * Format: int32
             * @description Optional last page of the topic within its source. If both pages are present, pageEnd must be >= pageStart.
             */
            pageEnd?: number;
            /**
             * Format: int32
             * @description Optional syllabus position; server assigns one if omitted.
             */
            order?: number;
        };
        /** @description A paginated page of topics (Page<Topic> per CONTRACTS.md §C11). */
        PageOfTopic: {
            /** @description The topics on this page. */
            items: components["schemas"]["Topic"][];
            /**
             * Format: int32
             * @description Total number of topics matching the query.
             */
            total: number;
            /**
             * Format: int32
             * @description 1-based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description Number of items per page.
             */
            pageSize: number;
        };
        /** @description The result of starting an attempt — the attempt plus its delivered questions. */
        StartAttemptResult: {
            attempt: components["schemas"]["ExamAttempt"];
            /** @description The delivered questions, in delivery order, without the answer key. */
            questions: components["schemas"]["DeliveredQuestion"][];
        };
        /** @description The result of submitting an attempt — the graded attempt plus the emitted ScoreEvent. */
        SubmitAttemptResult: {
            attempt: components["schemas"]["ExamAttempt"];
            scoreEvent: components["schemas"]["ScoreEvent"];
        };
        /** @description Body to sign a student in for an exam session. */
        StudentSignIn: {
            /** @description The student signing in. */
            studentId: string;
            /** @description Optional PIN gating the student sign-in. */
            pin?: string;
        };
        /** @description The response of a WebAuthn ceremony step. During the begin step it carries opaque ceremony options; on a successful finish it carries the established Session. Both fields are optional; exactly one is present per step. */
        AuthResult: {
            options?: components["schemas"]["WebAuthnCeremony"];
            session?: components["schemas"]["Session"];
        };
        /** @description A student's progress summary: per-topic mastery, the current streak, and recent attempt history. */
        Progress: {
            /** @description The student this progress belongs to. */
            studentId: string;
            /** @description Per-topic mastery levels (0–100). */
            mastery: components["schemas"]["TopicMastery"][];
            /** @description Current consecutive-pass streak (in days). */
            streak: number;
            /** @description Recent exam attempts, newest first. */
            history: components["schemas"]["ExamAttempt"][];
        };
        /** @description A single topic's mastery level for a student. */
        TopicMastery: {
            /** @description The topic this mastery is for. */
            topicId: string;
            /** @description Mastery level as a whole percentage (0–100). */
            mastery: number;
        };
    };
    responses: {
        /** @description An error occurred; the body is an RFC 7807-style problem. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Resource identifier (UUID/cuid). */
        IdPath: string;
        /** @description 1-based page number to return. */
        PageParam: number;
        /** @description Maximum number of items per page. */
        PageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSubjects: {
        parameters: {
            query?: {
                /** @description 1-based page number to return. */
                page?: components["parameters"]["PageParam"];
                /** @description Maximum number of items per page. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of subjects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfSubject"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubject"];
            };
        };
        responses: {
            /** @description The created subject. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subject. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subject"];
            };
        };
        responses: {
            /** @description The updated subject. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subject was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Filter sources to a single subject. */
                subjectId?: string;
                /** @description 1-based page number to return. */
                page?: components["parameters"]["PageParam"];
                /** @description Maximum number of items per page. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfSource"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSource"];
            };
        };
        responses: {
            /** @description The created source. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listTopics: {
        parameters: {
            query?: {
                /** @description Filter topics to a single subject. */
                subjectId?: string;
                /** @description 1-based page number to return. */
                page?: components["parameters"]["PageParam"];
                /** @description Maximum number of items per page. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of topics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfTopic"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopic"];
            };
        };
        responses: {
            /** @description The created topic. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The topic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Topic"];
            };
        };
        responses: {
            /** @description The updated topic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The topic was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listExamDefinitions: {
        parameters: {
            query?: {
                /** @description Filter exam definitions to a single subject. */
                subjectId?: string;
                /** @description 1-based page number to return. */
                page?: components["parameters"]["PageParam"];
                /** @description Maximum number of items per page. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of exam definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfExamDefinition"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createExamDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamDefinition"];
            };
        };
        responses: {
            /** @description The created exam definition. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDefinition"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getExamDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exam definition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDefinition"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateExamDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamDefinition"];
            };
        };
        responses: {
            /** @description The updated exam definition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDefinition"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteExamDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exam definition was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                /** @description Filter questions to a single subject. */
                subjectId?: string;
                /** @description Filter questions to a single topic. */
                topicId?: string;
                /** @description 1-based page number to return. */
                page?: components["parameters"]["PageParam"];
                /** @description Maximum number of items per page. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of questions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfQuestion"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestion"];
            };
        };
        responses: {
            /** @description The created question. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The question. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Question"];
            };
        };
        responses: {
            /** @description The updated question. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The question was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The student profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Student"];
            };
        };
        responses: {
            /** @description The updated student profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description The updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAttempts: {
        parameters: {
            query?: {
                /** @description Filter attempts to a single student. */
                studentId?: string;
                /** @description 1-based page number to return. */
                page?: components["parameters"]["PageParam"];
                /** @description Maximum number of items per page. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of exam attempts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfExamAttempt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    startAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAttempt"];
            };
        };
        responses: {
            /** @description The started attempt and its delivered questions. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartAttemptResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attempt (delivered, no answers). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttempt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    submitAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAttempt"];
            };
        };
        responses: {
            /** @description The graded attempt and the emitted score event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAttemptResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAttemptResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (UUID/cuid). */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The graded attempt with answers revealed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttempt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAuthnCeremony"];
            };
        };
        responses: {
            /** @description Ceremony options, or a Session on a successful finish. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAuthnCeremony"];
            };
        };
        responses: {
            /** @description Ceremony options, or a Session on a successful finish. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    authStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentSignIn"];
            };
        };
        responses: {
            /** @description The student session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProgress: {
        parameters: {
            query?: {
                /** @description The student whose progress to return. */
                studentId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The student's progress summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
